### ISSUE TITLE
Lab1

### ISSUE THREAD

**Issue by fantkolja** [naazarchiik/DesignPatterns#1]
- wrong arrow direction 
![image](https://github.com/naazarchiik/DesignPatterns/assets/13898415/1ecb63c3-b349-45f9-a31c-4ec90d169764)
- for such [big strings](https://github.com/naazarchiik/DesignPatterns/blob/master/Lab1/ClassLibrary/Reporting.cs#L54) it's probably more convenient to use StringBuilder 
- you could also move each of [these checks](https://github.com/naazarchiik/DesignPatterns/blob/master/Lab1/ClassLibrary/Reporting.cs#L25-L28) into a separate method, e.g. `_validateNotNull`
- You could even create a separate utility class Validator with those checks

**Comment by naazarchiik** [comment]
issues were taken into account and corrected
